version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
  - package-ecosystem: pip
    directory: "/ci"
    schedule:
      interval: weekly
    groups:
      pip:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: "/app"
    schedule:
      interval: weekly
    groups:
      npm:
        patterns: ["*"]
