/* EW shared pure logic. Loaded by the dashboard and overlay as a plain script
   (window.EWCore) and by node --test via require(). No DOM, no Electron.
   Plan 107: the code lives in per-feature parts under core/ (one file per
   domain, listed in PARTS). Each part is a plain script that registers an
   install(K) on window.EWCoreParts (require() returns it under node); this
   file installs them in PARTS order into one shared namespace K, binds the
   few forward references, and re-exports the same public surface as before.
   The pages load every core/<part>.part.js before this file. */
(function (root) {
  'use strict';

  const SERVER = 'http://127.0.0.1:8940';

  const PARTS = ['base', 'market', 'entry', 'bus', 'today', 'progress', 'grind', 'events',
    'deadeye', 'ocr', 'leveling', 'bosses', 'home', 'settings', 'inventory', 'shell', 'notify'];
  const NODE = typeof module !== 'undefined' && module.exports;
  const K = { SERVER: SERVER };
  const links = PARTS.map(function (name) {
    const install = NODE ? require('./core/' + name + '.part.js') : (root.EWCoreParts || {})[name];
    if (typeof install !== 'function') throw new Error('EWCore part missing: ' + name);
    return install(K);
  });
  links.forEach(function (link) { link(); });

  const { BOOK_SIZES, BOSS_DRIFT_MAX_LINES, BUFF_DEFAULTS, BUFF_MINUTES, CLAIM_TIMER_S,
    DAY_NAMES, DEADEYE_DRAFT_MS, DEADEYE_LEVELS, DEADEYE_SECTIONS, DEADLINE_STATES,
    DEFAULT_HOTKEYS, ENHANCE_MAX_FS, ENHANCE_STEPS, EVENTS_SOON_S, EVENT_KINDS, EXTERNAL_HOSTS,
    FS_KINDS, GAME_CONFIG_HINT, GAME_SHOTS_MAX, GAME_STATES, HEALTH_DEAD_MS, IMP_TYPES,
    INCIDENT_KEYS, LABELS, LADDER_MIN, LEVEL_MAX, MARKET_ALERTS, MOUNT_KINDS, NOTE_MAX,
    NOTIFY_BODY_MAX, NOTIFY_RATE, NOTIFY_RULES, NOTIFY_TITLE_MAX, OBJ_KINDS, OCR_NAME_MAX,
    OCR_TEXT_MAX, OPEN_RATE, OVERLAY_ANCHORS, OVERLAY_MODES, OVERLAY_ROWS, OVERLAY_SIZE,
    OVERLAY_WIDGETS, PALETTE_COMMANDS, PALETTE_ROUTES, PORTRAIT_HINT, POST_ROUTES,
    PROFILE_HISTORY_PATH, QUIET_ALLOW, QUIET_STATES, SEARCH_DEBOUNCE_MS, SETTINGS_FIELDS,
    SETTINGS_GROUPS, SETTINGS_KEYS, SPOT_GOALS, THEMES, TOAST_MAX, TOAST_MS, TOAST_ONCE_MS,
    TOAST_TEXT_MAX, VERSION_POLL_MS, WIDGETS, ZONES, agrisLine, alertFor, autoWatchBadge,
    backoffMs, bandStrip, booksLine, booksToNextText, bossDriftBanner, bossGarmothText,
    bossRows, bossSuggested, bossTicks, bracketLines, buffRowView, buffRows, buffsLive,
    calcQuery, claimBody, claimDueHits, claimLine, claimPlace, claimRows, classOfTab,
    collapsedKey, commitsDiffer, composeNow, countText, craftFormOf, craftSummary, createBus,
    currencyBalanceBody, currencyPill, currencyRows, currencyText, currencyWishBody,
    currencyWishText, deadlineAlert, deadlineBrief, deadlineLine, deadlinePill, depthBars,
    derivedText, diceLine, diceSuggest, draftDecode, draftEncode, draftKey, draftPending,
    draftsToRestore, dropView, enhanceFamilyGuess, enhancePath, enhanceSubSteps, enumOptions,
    epochText, epochTitle, evLine, eventDaysLeft, eventGameRows, eventRows, eventTickBody,
    eventsThisWeek, externalUrl, fmtAge, fmtBossRow, fmtCalc, fmtClock, fmtDays, fmtDaysLeft,
    fmtDuration, fmtDurationShort, fmtElapsed, fmtEta, fmtEv, fmtLeft, fmtLevelLine, fmtLocal,
    fmtMonthDay, fmtRate, fmtResetCountdown, fmtResetRule, fmtShopLine, fmtShopping, fmtSilver,
    fmtSilverExact, fmtStacks, fmtTarget, fmtWeeklyGate, freshness, galleryMove, gameEventText,
    gameSinceText, gameStateLabel, gameTimeMs, gateChips, groupItems, gsTotal, healthPill,
    historyRows, historyStats, hotAutoText, hotLive, hotUntilText, hotWindowView, hotkeys,
    imperialBest, imperialCpText, imperialReset, imperialRows, imperialUnpriced,
    invDerivedLines, invNextLines, invSaleRows, invSourceRows, invSummaryLines, invTownRows,
    isCollapsed, isDiceItem, isDone, itemFreshness, itemRule, labelHint, ladderStep,
    lastDailyReset, lastResetOf, lastWeeklyReset, levelIndex, levelingLine, lifeskillTrends,
    lifeskillView, liveElapsed, localToUtcIso, loginDayText, loginDays, loginMarkBody,
    loginPill, loginTodayText, loginTrackBody, loginWeekendText, lootHintText, lootImportCounts,
    lootImportText, lootPrefill, maintInText, maintLine, maintLossHits, marketPill, matchSpot,
    minimapZone, mountLabel, mountsFernLine, mountsOddsLine, muteOptions, muteValue,
    netProceeds, nextDailyReset, nextResetOf, nextWeeklyReset, normalizeBooks, normalizeDice,
    normalizeGame, normalizeLeveling, normalizeLootOcr, normalizeOcr, normalizeOcrAuto,
    normalizeTabs, notOnServer, noticeAddBody, noticeAutoRows, noticeDismissBody, noticeEndText,
    noticeRows, noticeStatus, noticeSteamHint, noticeUndoBody, notifyArg, notifyLedger,
    notifyPrefs, notifyPrefsFromArg, notifyRules, notifySilent, nowAlerts, nowDailies,
    nowMaintDigest, nowOnboarding, nowSession, nowSummary, nowTimers, nowWhatNow, ocrAutoHead,
    ocrAutoLabel, ocrBuffBody, ocrBuffLabel, ocrFixBody, ocrFixHint, ocrSilverH, ocrSilverInput,
    onboardingRows, orderTabs, ovQuiet, ovServerRowHidden, overlayBounds, overlayConfig,
    overlayContext, overlayHeight, overlayRowOrder, overlayStyleFromQuery, overlayStyleQuery,
    overlayWidgets, overrideBadge, overrideBadges, overridePill, overrideRows, pairProfit,
    paletteIndex, paletteKey, paletteMode, paletteSearch, paletteSuggest, paletteTitle,
    parseAgrisForm, parseBookForm, parseCharacterForm, parseCollapsed, parseCommand,
    parseCraftForm, parseCraftLines, parseCronsForm, parseDuration, parseEpochForm,
    parseEventForm, parseFernRate, parseFs, parseFsForm, parseGrindForm, parseHotForm,
    parseImperialBox, parseImperialCp, parseInvSale, parseInvSetForm, parseInvSourceForm,
    parseInvTownForm, parseLadder, parseLocalDateTime, parseLocalTime, parseMaterialsForm,
    parseMilestones, parseMountForm, parseObjectiveForm, parsePetForm, parseSampleForm,
    parseSettingInput, parseShopForm, parseSilver, parseStepForm, parseTodayForm,
    parseTrackForm, parseWatchForm, patchNote, pendingStop, pendingStopText, petCoverageLines,
    petExchangeLines, petRows, petSpeciesOptions, pollDue, pollPaused, portraitCard,
    portraitChip, portraitGallery, postToast, preorderBadge, preorderState, presetForm,
    profilePill, profileRows, profileSignalOff, profileTrends, promptGate, ptOffsetHours,
    ptToUtc, rateLimiter, reconcile, rectInside, rectsIntersect, renderMarkdown,
    resetCountdownView, resetKey, resetPresets, resetRuleView, searchPath, searchQuery,
    searchRows, seasonGroups, seasonLine, seedOptions, serializeCollapsed, serverRows,
    sessionPill, sessionSilver, settingDetectedNote, settingInputText, settingLocalNote,
    settingsBody, settingsEffects, settingsRows, shopWatchBody, signalPill, signalRow,
    signalRows, silverPerHour, soonestBuff, soonestEvent, sortSpots, sourceFreshness, sparkPath,
    spotGapText, spotName, spotNeedText, spotRecs, spotsPath, suggestAddBody, suggestStatus,
    suggestedRows, summaryRows, tabBadges, tabKey, tabOfClass, targetInput, themeAttr,
    tickerRows, tickerTrack, toastQueue, todayAutoMark, todayAutoTitle, todayReady,
    toggleCollapsed, trackPct, trashPileText, uiScale, validAccelerator, validBossesBody,
    validCraftingBody, validDeadeyeBody, validEventsBody, validGrindBody, validImperialBody,
    validInventoryBody, validLevelingBody, validMountsBody, validMute, validNotify,
    validOcrBody, validOnboardingBody, validOpenExternal, validPetsBody, validPortraitsBody,
    validPost, validProfileBase, validProgressBody, validResetRule, validSettingsBody,
    validTodayBody, validWatchBody, watchAlert, weeklyPlan, whatNowActions, whatNowLeft,
    whatNowLine, widgetsFromQuery, widgetsQuery, widgetsTurnedOn, withStep, withTick, xpPresets,
    zeroPill, zoneCapText, zoneKillsText, zoneLevelText } = K;

  const api = {
    EXTERNAL_HOSTS: EXTERNAL_HOSTS,
    OPEN_RATE: OPEN_RATE,
    externalUrl: externalUrl,
    validOpenExternal: validOpenExternal,
    DEADEYE_DRAFT_MS: DEADEYE_DRAFT_MS,
    draftKey: draftKey,
    draftEncode: draftEncode,
    draftDecode: draftDecode,
    draftPending: draftPending,
    draftsToRestore: draftsToRestore,
    TOAST_MAX: TOAST_MAX,
    TOAST_TEXT_MAX: TOAST_TEXT_MAX,
    TOAST_MS: TOAST_MS,
    NOTIFY_TITLE_MAX: NOTIFY_TITLE_MAX,
    NOTIFY_BODY_MAX: NOTIFY_BODY_MAX,
    NOTIFY_RATE: NOTIFY_RATE,
    NOTIFY_RULES: NOTIFY_RULES,
    toastQueue: toastQueue,
    TOAST_ONCE_MS: TOAST_ONCE_MS,
    LADDER_MIN: LADDER_MIN,
    QUIET_STATES: QUIET_STATES,
    QUIET_ALLOW: QUIET_ALLOW,
    parseLadder: parseLadder,
    ladderStep: ladderStep,
    promptGate: promptGate,
    postToast: postToast,
    notifyPrefs: notifyPrefs,
    notifySilent: notifySilent,
    notifyArg: notifyArg,
    notifyPrefsFromArg: notifyPrefsFromArg,
    notifyRules: notifyRules,
    fmtBossRow: fmtBossRow,
    bossRows: bossRows,
    bossTicks: bossTicks,
    bossSuggested: bossSuggested,
    bossGarmothText: bossGarmothText,
    bossDriftBanner: bossDriftBanner,
    BOSS_DRIFT_MAX_LINES: BOSS_DRIFT_MAX_LINES,
    validBossesBody: validBossesBody,
    notifyLedger: notifyLedger,
    validNotify: validNotify,
    rateLimiter: rateLimiter,
    SERVER: SERVER,
    GAME_STATES: GAME_STATES,
    GAME_SHOTS_MAX: GAME_SHOTS_MAX,
    GAME_CONFIG_HINT: GAME_CONFIG_HINT,
    gameStateLabel: gameStateLabel,
    gameTimeMs: gameTimeMs,
    gameEventText: gameEventText,
    normalizeGame: normalizeGame,
    fmtClock: fmtClock,
    gameSinceText: gameSinceText,
    OCR_NAME_MAX: OCR_NAME_MAX,
    OCR_TEXT_MAX: OCR_TEXT_MAX,
    validOcrBody: validOcrBody,
    normalizeOcrAuto: normalizeOcrAuto,
    ocrAutoLabel: ocrAutoLabel,
    ocrAutoHead: ocrAutoHead,
    ocrFixBody: ocrFixBody,
    ocrFixHint: ocrFixHint,
    ocrSilverH: ocrSilverH,
    normalizeOcr: normalizeOcr,
    ocrBuffBody: ocrBuffBody,
    ocrSilverInput: ocrSilverInput,
    ocrBuffLabel: ocrBuffLabel,
    normalizeLootOcr: normalizeLootOcr,
    lootImportCounts: lootImportCounts,
    lootImportText: lootImportText,
    lastDailyReset: lastDailyReset,
    lastWeeklyReset: lastWeeklyReset,
    validResetRule: validResetRule,
    itemRule: itemRule,
    lastResetOf: lastResetOf,
    nextResetOf: nextResetOf,
    fmtResetRule: fmtResetRule,
    fmtResetCountdown: fmtResetCountdown,
    resetRuleView: resetRuleView,
    resetCountdownView: resetCountdownView,
    fmtWeeklyGate: fmtWeeklyGate,
    weeklyPlan: weeklyPlan,
    resetKey: resetKey,
    resetPresets: resetPresets,
    presetForm: presetForm,
    isDone: isDone,
    eventDaysLeft: eventDaysLeft,
    fmtDaysLeft: fmtDaysLeft,
    groupItems: groupItems,
    withTick: withTick,
    validTodayBody: validTodayBody,
    parseTodayForm: parseTodayForm,
    gsTotal: gsTotal,
    bracketLines: bracketLines,
    trackPct: trackPct,
    seedOptions: seedOptions,
    gateChips: gateChips,
    withStep: withStep,
    OBJ_KINDS: OBJ_KINDS,
    fmtTarget: fmtTarget,
    seasonGroups: seasonGroups,
    seasonLine: seasonLine,
    parseObjectiveForm: parseObjectiveForm,
    targetInput: targetInput,
    validProgressBody: validProgressBody,
    parseCharacterForm: parseCharacterForm,
    parseTrackForm: parseTrackForm,
    profilePill: profilePill,
    profileSignalOff: profileSignalOff,
    signalRow: signalRow,
    PROFILE_OFF_TEXT: 'Profile source off - set a self-hosted base in Settings',
    validProfileBase: validProfileBase,
    profileRows: profileRows,
    BUFF_DEFAULTS: BUFF_DEFAULTS,
    BUFF_MINUTES: BUFF_MINUTES,
    silverPerHour: silverPerHour,
    fmtElapsed: fmtElapsed,
    liveElapsed: liveElapsed,
    buffsLive: buffsLive,
    soonestBuff: soonestBuff,
    buffRows: buffRows,
    xpPresets: xpPresets,
    patchNote: patchNote,
    epochTitle: epochTitle,
    sortSpots: sortSpots,
    spotName: spotName,
    validGrindBody: validGrindBody,
    dropView: dropView,
    agrisLine: agrisLine,
    parseGrindForm: parseGrindForm,
    lootHintText: lootHintText,
    sessionSilver: sessionSilver,
    trashPileText: trashPileText,
    SPOT_GOALS: SPOT_GOALS,
    spotsPath: spotsPath,
    spotNeedText: spotNeedText,
    spotGapText: spotGapText,
    spotRecs: spotRecs,
    zoneKillsText: zoneKillsText,
    zoneLevelText: zoneLevelText,
    zoneCapText: zoneCapText,
    matchSpot: matchSpot,
    EVENT_KINDS: EVENT_KINDS,
    EVENTS_SOON_S: EVENTS_SOON_S,
    fmtLeft: fmtLeft,
    eventRows: eventRows,
    CLAIM_TIMER_S: CLAIM_TIMER_S,
    claimPlace: claimPlace,
    claimLine: claimLine,
    claimRows: claimRows,
    claimBody: claimBody,
    claimDueHits: claimDueHits,
    soonestEvent: soonestEvent,
    localToUtcIso: localToUtcIso,
    validEventsBody: validEventsBody,
    parseEventForm: parseEventForm,
    suggestedRows: suggestedRows,
    loginDays: loginDays,
    loginDayText: loginDayText,
    loginTodayText: loginTodayText,
    loginPill: loginPill,
    loginWeekendText: loginWeekendText,
    loginTrackBody: loginTrackBody,
    loginMarkBody: loginMarkBody,
    currencyRows: currencyRows,
    currencyText: currencyText,
    currencyPill: currencyPill,
    currencyWishText: currencyWishText,
    currencyWishBody: currencyWishBody,
    currencyBalanceBody: currencyBalanceBody,
    eventGameRows: eventGameRows,
    eventTickBody: eventTickBody,
    suggestAddBody: suggestAddBody,
    suggestStatus: suggestStatus,
    noticeRows: noticeRows,
    noticeAddBody: noticeAddBody,
    noticeDismissBody: noticeDismissBody,
    noticeAutoRows: noticeAutoRows,
    noticeUndoBody: noticeUndoBody,
    noticeSteamHint: noticeSteamHint,
    hotAutoText: hotAutoText,
    noticeEndText: noticeEndText,
    noticeStatus: noticeStatus,
    DEADEYE_LEVELS: DEADEYE_LEVELS,
    DEADEYE_SECTIONS: DEADEYE_SECTIONS,
    NOTE_MAX: NOTE_MAX,
    levelIndex: levelIndex,
    renderMarkdown: renderMarkdown,
    validDeadeyeBody: validDeadeyeBody,
    parseStepForm: parseStepForm,
    ENHANCE_MAX_FS: ENHANCE_MAX_FS,
    parseFs: parseFs,
    enhanceSubSteps: enhanceSubSteps,
    enhanceFamilyGuess: enhanceFamilyGuess,
    enhancePath: enhancePath,
    fmtEv: fmtEv,
    evLine: evLine,
    FS_KINDS: FS_KINDS,
    ENHANCE_STEPS: ENHANCE_STEPS,
    parseFsForm: parseFsForm,
    parseAgrisForm: parseAgrisForm,
    parseCronsForm: parseCronsForm,
    fmtStacks: fmtStacks,
    parseShopForm: parseShopForm,
    fmtShopLine: fmtShopLine,
    fmtShopping: fmtShopping,
    shopWatchBody: shopWatchBody,
    calcQuery: calcQuery,
    fmtCalc: fmtCalc,
    validLevelingBody: validLevelingBody,
    parseSampleForm: parseSampleForm,
    parseHotForm: parseHotForm,
    parseMilestones: parseMilestones,
    parseEpochForm: parseEpochForm,
    epochText: epochText,
    LEVEL_MAX: LEVEL_MAX,
    fmtRate: fmtRate,
    fmtEta: fmtEta,
    fmtDays: fmtDays,
    DAY_NAMES: DAY_NAMES,
    normalizeLeveling: normalizeLeveling,
    normalizeBooks: normalizeBooks,
    booksLine: booksLine,
    booksToNextText: booksToNextText,
    parseBookForm: parseBookForm,
    BOOK_SIZES: BOOK_SIZES,
    hotLive: hotLive,
    levelingLine: levelingLine,
    fmtLevelLine: fmtLevelLine,
    historyRows: historyRows,
    PROFILE_HISTORY_PATH: PROFILE_HISTORY_PATH,
    lifeskillView: lifeskillView,
    lifeskillTrends: lifeskillTrends,
    profileTrends: profileTrends,
    DEADLINE_STATES: DEADLINE_STATES,
    deadlineBrief: deadlineBrief,
    fmtMonthDay: fmtMonthDay,
    deadlinePill: deadlinePill,
    deadlineLine: deadlineLine,
    deadlineAlert: deadlineAlert,
    composeNow: composeNow,
    nowTimers: nowTimers,
    nowDailies: nowDailies,
    nowSession: nowSession,
    nowAlerts: nowAlerts,
    collapsedKey: collapsedKey,
    parseCollapsed: parseCollapsed,
    toggleCollapsed: toggleCollapsed,
    serializeCollapsed: serializeCollapsed,
    isCollapsed: isCollapsed,
    whatNowActions: whatNowActions,
    whatNowLeft: whatNowLeft,
    whatNowLine: whatNowLine,
    nowWhatNow: nowWhatNow,
    nowMaintDigest: nowMaintDigest,
    maintInText: maintInText,
    maintLossHits: maintLossHits,
    pendingStop: pendingStop,
    pendingStopText: pendingStopText,
    sessionPill: sessionPill,
    summaryRows: summaryRows,
    nowSummary: nowSummary,
    validOnboardingBody: validOnboardingBody,
    onboardingRows: onboardingRows,
    nowOnboarding: nowOnboarding,
    eventsThisWeek: eventsThisWeek,
    countText: countText,
    zeroPill: zeroPill,
    tabBadges: tabBadges,
    tabKey: tabKey,
    orderTabs: orderTabs,
    overlayWidgets: overlayWidgets,
    WIDGETS: WIDGETS,
    widgetsQuery: widgetsQuery,
    widgetsFromQuery: widgetsFromQuery,
    OVERLAY_MODES: OVERLAY_MODES,
    OVERLAY_WIDGETS: OVERLAY_WIDGETS,
    OVERLAY_ROWS: OVERLAY_ROWS,
    overlayContext: overlayContext,
    widgetsTurnedOn: widgetsTurnedOn,
    overlayRowOrder: overlayRowOrder,
    maintLine: maintLine,
    OVERLAY_ANCHORS: OVERLAY_ANCHORS,
    OVERLAY_SIZE: OVERLAY_SIZE,
    overlayConfig: overlayConfig,
    overlayBounds: overlayBounds,
    minimapZone: minimapZone,
    rectInside: rectInside,
    rectsIntersect: rectsIntersect,
    overlayHeight: overlayHeight,
    overlayStyleQuery: overlayStyleQuery,
    overlayStyleFromQuery: overlayStyleFromQuery,
    ovQuiet: ovQuiet,
    isDiceItem: isDiceItem,
    normalizeDice: normalizeDice,
    diceLine: diceLine,
    diceSuggest: diceSuggest,
    todayAutoMark: todayAutoMark,
    todayReady: todayReady,
    todayAutoTitle: todayAutoTitle,
    ovServerRowHidden: ovServerRowHidden,
    validPetsBody: validPetsBody,
    parsePetForm: parsePetForm,
    petRows: petRows,
    petCoverageLines: petCoverageLines,
    petExchangeLines: petExchangeLines,
    petSpeciesOptions: petSpeciesOptions,
    validInventoryBody: validInventoryBody,
    validCraftingBody: validCraftingBody,
    parseCraftLines: parseCraftLines,
    parseCraftForm: parseCraftForm,
    craftFormOf: craftFormOf,
    craftSummary: craftSummary,
    parseInvSetForm: parseInvSetForm,
    parseInvSourceForm: parseInvSourceForm,
    parseInvTownForm: parseInvTownForm,
    parseInvSale: parseInvSale,
    invSummaryLines: invSummaryLines,
    invDerivedLines: invDerivedLines,
    invSourceRows: invSourceRows,
    invNextLines: invNextLines,
    invTownRows: invTownRows,
    invSaleRows: invSaleRows,
    IMP_TYPES: IMP_TYPES,
    validImperialBody: validImperialBody,
    imperialRows: imperialRows,
    imperialReset: imperialReset,
    imperialCpText: imperialCpText,
    imperialBest: imperialBest,
    imperialUnpriced: imperialUnpriced,
    parseImperialBox: parseImperialBox,
    parseImperialCp: parseImperialCp,
    validPost: validPost,
    POST_ROUTES: POST_ROUTES,
    PALETTE_COMMANDS: PALETTE_COMMANDS,
    PALETTE_ROUTES: PALETTE_ROUTES,
    parseCommand: parseCommand,
    paletteSuggest: paletteSuggest,
    paletteMode: paletteMode,
    paletteIndex: paletteIndex,
    paletteSearch: paletteSearch,
    paletteKey: paletteKey,
    paletteTitle: paletteTitle,
    portraitChip: portraitChip,
    portraitCard: portraitCard,
    portraitGallery: portraitGallery,
    galleryMove: galleryMove,
    validPortraitsBody: validPortraitsBody,
    classOfTab: classOfTab,
    tabOfClass: tabOfClass,
    PORTRAIT_HINT: PORTRAIT_HINT,
    MOUNT_KINDS: MOUNT_KINDS,
    validMountsBody: validMountsBody,
    mountLabel: mountLabel,
    mountsFernLine: mountsFernLine,
    mountsOddsLine: mountsOddsLine,
    parseMountForm: parseMountForm,
    parseMaterialsForm: parseMaterialsForm,
    parseFernRate: parseFernRate,
    THEMES: THEMES,
    SETTINGS_GROUPS: SETTINGS_GROUPS,
    SETTINGS_FIELDS: SETTINGS_FIELDS,
    LABELS: LABELS,
    labelHint: labelHint,
    settingsRows: settingsRows,
    enumOptions: enumOptions,
    settingLocalNote: settingLocalNote,
    SETTINGS_KEYS: SETTINGS_KEYS,
    INCIDENT_KEYS: INCIDENT_KEYS,
    validMute: validMute,
    muteValue: muteValue,
    muteOptions: muteOptions,
    validSettingsBody: validSettingsBody,
    parseSettingInput: parseSettingInput,
    settingInputText: settingInputText,
    settingDetectedNote: settingDetectedNote,
    settingsBody: settingsBody,
    settingsEffects: settingsEffects,
    themeAttr: themeAttr,
    uiScale: uiScale,
    fmtSilver: fmtSilver,
    fmtSilverExact: fmtSilverExact,
    SEARCH_DEBOUNCE_MS: SEARCH_DEBOUNCE_MS,
    searchQuery: searchQuery,
    searchPath: searchPath,
    searchRows: searchRows,
    sparkPath: sparkPath,
    historyStats: historyStats,
    alertFor: alertFor,
    MARKET_ALERTS: MARKET_ALERTS,
    watchAlert: watchAlert,
    autoWatchBadge: autoWatchBadge,
    bandStrip: bandStrip,
    depthBars: depthBars,
    fmtAge: fmtAge,
    derivedText: derivedText,
    marketPill: marketPill,
    itemFreshness: itemFreshness,
    validWatchBody: validWatchBody,
    parseWatchForm: parseWatchForm,
    pollDue: pollDue,
    createBus: createBus,
    pollPaused: pollPaused,
    reconcile: reconcile,
    netProceeds: netProceeds,
    parseSilver: parseSilver,
    parseDuration: parseDuration,
    fmtDurationShort: fmtDurationShort,
    ptOffsetHours: ptOffsetHours,
    ptToUtc: ptToUtc,
    parseLocalTime: parseLocalTime,
    parseLocalDateTime: parseLocalDateTime,
    fmtLocal: fmtLocal,
    hotWindowView: hotWindowView,
    hotUntilText: hotUntilText,
    lootPrefill: lootPrefill,
    buffRowView: buffRowView,
    ZONES: ZONES,
    pairProfit: pairProfit,
    preorderState: preorderState,
    preorderBadge: preorderBadge,
    tickerRows: tickerRows,
    tickerTrack: tickerTrack,
    nextDailyReset: nextDailyReset,
    nextWeeklyReset: nextWeeklyReset,
    fmtDuration: fmtDuration,
    freshness: freshness,
    normalizeTabs: normalizeTabs,
    backoffMs: backoffMs,
    HEALTH_DEAD_MS: HEALTH_DEAD_MS,
    VERSION_POLL_MS: VERSION_POLL_MS,
    commitsDiffer: commitsDiffer,
    healthPill: healthPill,
    notOnServer: notOnServer,
    sourceFreshness: sourceFreshness,
    signalRows: signalRows,
    signalPill: signalPill,
    overrideBadge: overrideBadge,
    overrideBadges: overrideBadges,
    overrideRows: overrideRows,
    overridePill: overridePill,
    serverRows: serverRows,
    validAccelerator: validAccelerator,
    hotkeys: hotkeys,
    DEFAULT_HOTKEYS: DEFAULT_HOTKEYS
  };
  if (NODE) module.exports = api;
  else root.EWCore = api;
})(typeof self !== 'undefined' ? self : this);
