'use strict';
// Plan 030: Settings tab form model (pure helpers in ewcore) + shell wiring.
const test = require('node:test');
const assert = require('node:assert');
const fs = require('fs');
const path = require('path');
const C = require('../shared/ewcore');

const APP = path.join(__dirname, '..');
const read = (p) => fs.readFileSync(path.join(APP, p), 'utf8');

test('groups in plan order, every key dotted, no secrets or loop keys', () => {
  assert.deepStrictEqual(C.SETTINGS_GROUPS.map((g) => g.title),
    ['Overlay', 'Hotkeys', 'Profile', 'Appearance', 'Notifications', 'Events', 'Market',
      'Play session', 'Screenshots (OCR)', 'Game folders', 'Checklist']);
  for (const k of C.SETTINGS_KEYS) {
    assert.match(k, /^[a-z]+(\.[A-Za-z_]+)+$/, k);
    assert.doesNotMatch(k, /^(secrets|loop)\b/, k);
  }
  assert.strictEqual(new Set(C.SETTINGS_KEYS).size, C.SETTINGS_KEYS.length);
});

test('client allowlist matches the server allowlist key for key', () => {
  const py = fs.readFileSync(path.join(APP, '..', 'server', 'ew', 'settings.py'), 'utf8');
  const keys = new Set();
  for (const m of py.matchAll(/^\s+"([a-z]+\.[A-Za-z_.]+)": \(/gm)) keys.add(m[1]);
  const w = /WIDGETS = \{([^}]*)\}/.exec(py)[1].match(/"(\w+)"/g).map((s) => 'overlay.widgets.' + s.slice(1, -1));
  const n = /NOTIFY = \{([^}]*)\}/.exec(py)[1].match(/"(\w+)"/g).map((s) => 'notify.' + s.slice(1, -1));
  // Plan 067: one overlay.mode.<w> per widget, generated by the same loop.
  const m = w.map((k) => k.replace('overlay.widgets.', 'overlay.mode.'));
  assert.match(py, /SPEC\[f"overlay\.mode\.\{_w\}"\]/);
  w.concat(n, m).forEach((k) => keys.add(k));
  assert.deepStrictEqual([...keys].sort(), C.SETTINGS_KEYS.slice().sort());
});

test('validSettingsBody: allowlisted keys with valid values only', () => {
  assert.strictEqual(C.validSettingsBody({ set: { 'ui.theme': 'light', 'overlay.scale': 1.2 } }), true);
  assert.strictEqual(C.validSettingsBody({ set: { 'overlay.anchor': { x: 4, y: 5 } } }), true);
  assert.strictEqual(C.validSettingsBody({ set: { 'overlay.display': null } }), true);
  const bad = [null, {}, { set: {} }, { set: [] }, { set: { 'ui.theme': 'pink' } },
    { set: { 'secrets.ocr': { env: 'K' } } }, { set: { 'loop.max_notes_per_day': 9 } },
    { set: { 'overlay.anchor': { env: 'K' } } }, { set: { 'hotkeys.toggleOverlay': 'E' } },
    { set: { 'ui.scale': 1.5 } }, { set: { 'profile.family': 'a b' } }, { set: { 'notify.x': true } },
    { set: { 'ui.theme': 'dark' }, x: 1 }, { set: { 'overlay.anchor': { x: 100001, y: 0 } } },
    { set: { 'hotkeys.toggleOverlay': 'Control+'.repeat(10) + 'E' } },
    { set: { 'hotkeys.toggleOverlay': 'Control+Alt+F\n' } }, { set: { 'profile.family': 'abc\n' } }];
  for (const b of bad) assert.strictEqual(C.validSettingsBody(b), false, JSON.stringify(b));
  assert.strictEqual(C.validPost('/api/settings', { set: { 'coupons.check': false } }), true);
  assert.ok(C.POST_ROUTES.indexOf('/api/settings') >= 0);
});

test('parseSettingInput turns form text into typed values or a hint', () => {
  assert.deepStrictEqual(C.parseSettingInput('overlay.scale', ' 1.25 '), { value: 1.25 });
  assert.deepStrictEqual(C.parseSettingInput('overlay.display', ''), { value: null });
  assert.deepStrictEqual(C.parseSettingInput('overlay.display', '1'), { value: 1 });
  assert.deepStrictEqual(C.parseSettingInput('overlay.anchor', 'mr'), { value: 'mr' });
  assert.deepStrictEqual(C.parseSettingInput('overlay.anchor', '40, -3'), { value: { x: 40, y: -3 } });
  assert.deepStrictEqual(C.parseSettingInput('notify.gameExit', true), { value: true });
  assert.deepStrictEqual(C.parseSettingInput('profile.family', ''), { value: '' });
  assert.deepStrictEqual(C.parseSettingInput('hotkeys.showDashboard', 'Control+Shift+F2'),
    { value: 'Control+Shift+F2' });
  for (const [k, v] of [['overlay.scale', '2'], ['overlay.scale', 'abc'], ['overlay.display', '-1'],
    ['overlay.anchor', 'zz'], ['hotkeys.toggleOverlay', 'Q'], ['profile.family', 'x'],
    ['ui.theme', 'neon'], ['market.fame_pct', '1.6'], ['nope', '1']]) {
    const r = C.parseSettingInput(k, v);
    assert.ok(typeof r.error === 'string' && r.error && !('value' in r), k + '=' + v);
  }
  assert.match(C.parseSettingInput('hotkeys.toggleOverlay', 'Q').error, /modifier/);
});

test('plan 059: maintenance start is blank or HH:MM UTC', () => {
  assert.deepStrictEqual(C.parseSettingInput('events.maintenance_start_utc', ' 08:30 '), { value: '08:30' });
  assert.deepStrictEqual(C.parseSettingInput('events.maintenance_start_utc', ''), { value: '' });
  for (const v of ['8:30', '24:00', '07:60', 'noon']) {
    assert.match(C.parseSettingInput('events.maintenance_start_utc', v).error, /HH:MM/, v);
  }
  assert.strictEqual(C.validSettingsBody({ set: { 'events.notice_check': false } }), true);
  assert.strictEqual(C.validSettingsBody({ set: { 'events.maintenance_start_utc': 7 } }), false);
});

test('settingInputText round-trips through parseSettingInput', () => {
  const vals = { 'overlay.anchor': { x: 10, y: 20 }, 'overlay.display': null, 'overlay.scale': 1.1,
    'profile.family': 'Abc', 'ui.theme': 'system' };
  for (const k of Object.keys(vals)) {
    assert.deepStrictEqual(C.parseSettingInput(k, C.settingInputText(k, vals[k])), { value: vals[k] }, k);
  }
});

test('settingsBody keeps only changed allowlisted keys', () => {
  const saved = { 'ui.theme': 'dark', 'overlay.anchor': { x: 1, y: 2 }, 'overlay.scale': 1 };
  assert.strictEqual(C.settingsBody(saved, { 'ui.theme': 'dark', 'overlay.anchor': { x: 1, y: 2 } }), null);
  assert.deepStrictEqual(C.settingsBody(saved, { 'ui.theme': 'light', 'overlay.scale': 1, bogus: 1 }),
    { set: { 'ui.theme': 'light' } });
  assert.deepStrictEqual(C.settingsBody(saved, { 'overlay.anchor': 'tl' }), { set: { 'overlay.anchor': 'tl' } });
});

test('settingsEffects maps changed keys to app actions', () => {
  assert.deepStrictEqual(C.settingsEffects(['overlay.widgets.season']), { overlay: true, shell: false, theme: false });
  assert.deepStrictEqual(C.settingsEffects(['hotkeys.toggleOverlay']), { overlay: false, shell: true, theme: false });
  assert.deepStrictEqual(C.settingsEffects(['ui.scale', 'ui.theme']), { overlay: false, shell: true, theme: true });
  assert.deepStrictEqual(C.settingsEffects(null), { overlay: false, shell: false, theme: false });
});

test('themeAttr and uiScale', () => {
  assert.strictEqual(C.themeAttr('light', true), 'light');
  assert.strictEqual(C.themeAttr('dark', false), 'dark');
  assert.strictEqual(C.themeAttr('system', true), 'dark');
  assert.strictEqual(C.themeAttr('system', false), 'light');
  assert.strictEqual(C.themeAttr(undefined, false), 'dark');
  assert.strictEqual(C.uiScale({ ui: { scale: 1.2 } }), 1.2);
  for (const c of [{}, null, { ui: { scale: 2 } }, { ui: { scale: '1.1' } }, { ui: 5 }]) assert.strictEqual(C.uiScale(c), 1);
});

test('shell: settings IPC is payload-free, sender-checked, globalShortcut only', () => {
  const pre = read('preload.js');
  const m = read('main.js');
  assert.match(pre, /ipcRenderer\.invoke\('ew:reload-overlay'\)/);
  assert.match(pre, /ipcRenderer\.invoke\('ew:reload-shell'\)/);
  for (const ch of ['ew:reload-overlay', 'ew:reload-shell']) {
    const h = m.slice(m.indexOf("ipcMain.handle('" + ch + "'"));
    assert.match(h.slice(0, 400), /function \(event\) \{\s*if \(!dashboard \|\| event\.sender !== dashboard\.webContents\)/, ch);
  }
  assert.match(m, /setZoomFactor\(core\.uiScale\(/);
  assert.match(m, /globalShortcut\.register\(/);
  assert.doesNotMatch(m, /uiohook|iohook|robotjs|nut-js|SetWindowsHookEx|sendInputEvent/);
});

// ---- Plan 078 ----

const CAMEL = /[a-z][A-Z]/;
const DOTTED = /\b[a-z]+\.[a-z_]{2,}/; // a config key, not 'e.g.'

test('plan 078: no Settings label or option text is a code identifier', () => {
  for (const g of C.SETTINGS_GROUPS) {
    for (const f of g.fields) {
      assert.doesNotMatch(f.label, CAMEL, f.key + ': ' + f.label);
      assert.doesNotMatch(f.label, DOTTED, f.key + ': ' + f.label);
      if (f.type === 'enum') {
        for (const o of C.enumOptions(f)) assert.doesNotMatch(o.text, CAMEL, f.key);
      }
    }
  }
  for (const k of Object.keys(C.LABELS)) {
    assert.doesNotMatch(C.LABELS[k], CAMEL, k);
    assert.doesNotMatch(C.LABELS[k], DOTTED, k);
  }
  assert.strictEqual(C.LABELS.whatNow, 'What now');
  assert.strictEqual(C.LABELS['bdo.documents_dir'], 'Game folders > BDO Documents folder');
  assert.strictEqual(C.SETTINGS_FIELDS['notify.marketAlert'].label, C.LABELS.marketAlert);
});

test('plan 078: Overlay group renders one row per widget plus the six overlay settings', () => {
  const g = C.SETTINGS_GROUPS.find((x) => x.id === 'overlay');
  const rows = C.settingsRows(g);
  const modes = rows.filter((f) => f.key.indexOf('overlay.mode.') === 0);
  assert.strictEqual(modes.length, 9);
  assert.deepStrictEqual(modes.map((f) => f.key.slice(13)), C.WIDGETS);
  assert.deepStrictEqual(modes.map((f) => f.label), C.WIDGETS.map((w) => C.LABELS[w]));
  assert.deepStrictEqual(rows.filter((f) => f.key.indexOf('overlay.mode.') !== 0).map((f) => f.key),
    ['overlay.anchor', 'overlay.display', 'overlay.scale', 'overlay.opacity', 'overlay.auto', 'overlay.idle_min']);
  assert.strictEqual(rows.length, 15);
  assert.ok(rows.every((f) => f.key.indexOf('overlay.widgets.') !== 0), 'manual booleans not rendered');
  // Still allowlisted (the server keeps the keys until plan 080 removes them).
  assert.strictEqual(C.validSettingsBody({ set: { 'overlay.widgets.dice': true } }), true);
  // Every other group renders every field.
  for (const x of C.SETTINGS_GROUPS.filter((y) => y.id !== 'overlay')) {
    assert.strictEqual(C.settingsRows(x).length, x.fields.length, x.id);
  }
  assert.deepStrictEqual(C.settingsRows(null), []);
});

test('plan 078: widget mode select shows auto / always / never, stores auto | pin | block', () => {
  const f = C.SETTINGS_FIELDS['overlay.mode.dice'];
  assert.deepStrictEqual(C.enumOptions(f), [{ value: 'auto', text: 'auto' }, { value: 'pin', text: 'always' },
    { value: 'block', text: 'never' }]);
  for (const v of ['auto', 'pin', 'block']) {
    assert.deepStrictEqual(C.parseSettingInput('overlay.mode.dice', C.settingInputText('overlay.mode.dice', v)), { value: v });
  }
  assert.ok(C.parseSettingInput('overlay.mode.dice', 'always').error, 'display text is not a stored value');
  assert.deepStrictEqual(C.enumOptions(C.SETTINGS_FIELDS['ui.theme']).map((o) => o.value), ['system', 'dark', 'light']);
  assert.deepStrictEqual(C.enumOptions(null), []);
  const src = read('dashboard/settings.js');
  assert.match(src, /C\.settingsRows\(g\)/);
  assert.match(src, /C\.enumOptions\(f\)/);
});

test('plan 078: onboarding hints name the Settings field, not the config key', () => {
  assert.strictEqual(C.labelHint('Not found under Documents: Settings > bdo.documents_dir (its ScreenShot folder)'),
    'Not found under Documents: Settings > Game folders > BDO Documents folder (its ScreenShot folder)');
  assert.strictEqual(C.labelHint('Settings > profile.family turns on the profile card'),
    'Settings > Profile > Family name turns on the profile card');
  assert.strictEqual(C.labelHint('Settings > overlay.anchor picks'), 'Settings > Overlay > Anchor picks');
  assert.strictEqual(C.labelHint('Settings > bdo.install_dir'), 'Settings > Game folders > BDO install folder');
  assert.strictEqual(C.labelHint('Market > add items'), 'Market > add items');
  assert.strictEqual(C.labelHint(null), '');
  const rows = C.onboardingRows({ steps: [{ id: 'log', title: 'Point EW', hint: 'Settings > bdo.install_dir',
    link: { tab: 'settings', field: 'bdo.install_dir' }, done: false }] });
  assert.strictEqual(rows[0].note, 'Settings > Game folders > BDO install folder');
  assert.deepStrictEqual(rows[0].go, { tab: 'settings', field: 'bdo.install_dir' });
});

test('plan 078: a stored HH:MM UTC setting shows its local time beside it, UTC on hover', () => {
  const now = Date.parse('2026-10-06T12:00:00Z'); // PDT = UTC-7
  assert.deepStrictEqual(C.settingLocalNote('events.maintenance_start_utc', '07:00', { zone: 'pt', now: now }),
    { text: '= 00:00 local', title: 'UTC 07:00' });
  assert.deepStrictEqual(C.settingLocalNote('events.maintenance_start_utc', '02:30', { zone: 'pt', now: now }),
    { text: '= 19:30 local (day before)', title: 'UTC 02:30' });
  assert.strictEqual(C.settingLocalNote('events.maintenance_start_utc', '', { zone: 'pt', now: now }), null);
  assert.strictEqual(C.settingLocalNote('ui.theme', 'dark'), null);
  assert.match(read('dashboard/settings.js'), /C\.settingLocalNote\(f\.key, v\)/);
});

test('plan 078: zeroPill is blank at zero', () => {
  assert.strictEqual(C.zeroPill(0, 'session', 'sessions'), '');
  assert.strictEqual(C.zeroPill(1, 'session', 'sessions'), '1 session');
  assert.strictEqual(C.zeroPill(3, 'session', 'sessions'), '3 sessions');
  assert.strictEqual(C.zeroPill(2, 'open'), '2 open');
  for (const bad of [null, undefined, NaN, -1, '3']) assert.strictEqual(C.zeroPill(bad, 'x'), '');
});

test('dashboard: settings tab mounted, script loaded, min text 12px', () => {
  assert.match(read('dashboard/index.html'), /<script src="settings\.js"><\/script>/);
  assert.match(read('dashboard/dashboard.js'), /t\.id === 'settings' && window\.EWSettings/);
  const css = read('shared/ew.css');
  for (const m of css.matchAll(/font-size:\s*(\d+)px/g)) assert.ok(Number(m[1]) >= 12, m[0]);
});
